version: "3.7"

services:
  react-app:
    container_name: coding-challenge
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - talentspace-network
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_GRAPHQL_URL=http://localhost:8080/v1/graphql
      - REACT_APP_REALTIME_GRAPHQL_URL=ws://localhost:8080/v1/graphql
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - talentspace-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    networks:
      - talentspace-network
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      api: 5000
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
  api:
    depends_on:
    - graphql-engine
    container_name: express-api
    <<: &default
        build:
            context: ./api
            target: production
            dockerfile: ./Dockerfile
        networks:
            - talentspace-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    ports:
        - 5001:5000
        - 9229:9229
    environment:
      - PORT=5000
      - NODE_ENV=prod
      - NODE_APP_GRAPHQL_URL=http://graphql-engine:8080/v1/graphql
      - SMTP_LOGIN=apikey
      - SMTP_PASSWORD=
      - SMTP_HOST=smtp.sendgrid.net
      - SENDER_ADDRESS=
      - EMAIL_SCHEDULE=* 18 * * *
volumes:
  db_data:
networks:
    talentspace-network:
